# https://github.com/Homebrew/homebrew-bundle

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

tap "loadimpact/k6"
tap "twpayne/taps"

brew "bash"
brew "bash-completion"
brew "composer"
brew "docker"
brew "findutils"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "grep"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "mkcert"
brew "moreutils"
brew "node"
brew "openconnect"
brew "openssh"
brew "php-code-sniffer"
brew "phpunit"
brew "ruby"
brew "ssh-copy-id"

brew "loadimpact/k6/k6"
brew "twpayne/taps/chezmoi"

cask "docker"
cask "firefox-developer-edition"
cask "google-chrome-dev"
cask "jetbrains-toolbox"
cask "logitech-options"
cask "openconnect-gui"
cask "visual-studio-code"
cask "vlc"
