#!/usr/bin/env bash
# shellcheck disable=SC1091

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Load the shell dotfiles, and then some:
# * ~/.bash/path can be used to extend `$PATH`.
# * ~/.bash/extra can be used for other settings you don’t want to commit.
# shellcheck source=private_dot_bash/prompt
for file in ~/.bash/{\
path,\
prompt,\
exports,\
aliases,\
functions,\
extra,\
options,\
completion\
}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;
