#!/usr/bin/env bash

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# shellcheck source=dot_bash_profile
[ -n "$PS1" ] && source ~/.bash_profile;
