#!/usr/bin/env bash
# shellcheck disable=SC1091

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Load the shell dotfiles.
# ~/.bash/extra can be used for other settings you don’t want to commit.
for file in ~/.bash/{\
path,\
prompt,\
exports,\
aliases,\
functions,\
options,\
completion,\
extra\
}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;
