#!/usr/bin/env bash

##
## Bash pre-exec handler
## https://github.com/rcaloras/bash-preexec
##

if [ -f /home/linuxbrew/.linuxbrew/etc/profile.d/bash-preexec.sh ]; then
	source /home/linuxbrew/.linuxbrew/etc/profile.d/bash-preexec.sh
fi

##
## Bash completion handler
## https://github.com/Homebrew/brew
##

# Add tab completion for many Bash commands
if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
if [ -x "$(command -v brew)" ]; then
	HOMEBREW_PREFIX="$(brew --prefix)"
	if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
		BASH_COMPLETION_COMPAT_DIR="${HOMEBREW_PREFIX}/etc/bash_completion.d"
		source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
	else
		for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
			[[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
		done
	fi
fi

##
## Bash history handler
## https://github.com/ellie/atuin
##

if [ -x "$(command -v atuin)" ]; then
	eval "$(atuin init bash)"
fi

##
## Bash prompt handler
## https://github.com/starship/starship
##

# See prompt file
# if [ -x "$(command -v starship)" ]; then
# 	eval "$(starship init bash)";
# fi

##
## Bash custom handlers
##

# Enable tab completion for `g` by marking it as an alias for `git`
if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
	complete -o default -o nospace -F _git g;
fi

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
if [ -e "$HOME/.ssh/config" ]; then
	complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;
fi

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults;

# Add `killall` tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall;

# Add after `sudo` tab completion
complete -cf sudo
