#!/usr/bin/env bash

# set PATH so it includes krew's private bin if it exists
if [ -d "${KREW_ROOT:-$HOME/.krew}/bin" ] ; then
    PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# set PATH so it includes WSL bin if it exists
if [ -n "$WSL_EXEC_PATH" ] ; then
    PATH="$PATH:$WSL_EXEC_PATH"
fi

export PATH;
