#!/usr/bin/env bash

##
## Bash `$PATH` extension
##

# set PATH so it includes krew's private bin if it exists
if [ -d "${KREW_ROOT:-$HOME/.krew}/bin" ] ; then
    PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
fi

# set PATH so it includes volta's private bin if it exists
if [ -d "${VOLTA_HOME:-$HOME/.volta}/bin" ] ; then
    PATH="${VOLTA_HOME:-$HOME/.volta}/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# rustup shell setup
# affix colons on either side of $PATH to simplify matching
if [ -d "$HOME/.cargo/bin" ] ; then
    case ":${PATH}:" in
        *:"$HOME/.cargo/bin":*)
            ;;
        *)
            # Prepending path in case a system-installed rustc needs to be overridden
            PATH="$HOME/.cargo/bin:$PATH"
            ;;
    esac
fi

# set PATH so it includes WSL bin if it exists
if [ -n "$WSL_EXEC_PATH" ] ; then
    PATH="$PATH:$WSL_EXEC_PATH"
fi

export PATH;
