# https://github.com/topgrade-rs/topgrade

[misc]
# Disable specific steps - same options as the command line flag
disable = ["snap"]

# Ignore failures for these steps
ignore_failures = ["containers"]

# Don't ask for confirmations (no default value)
assume_yes = true

# Do not ask to retry failed steps (default: false)
no_retry = true

[git]
# How many repos to pull at max in parallel
# max_concurrency = 5

# Additional git repositories to pull
repos = [
    "~/projects/*/*/*/",
]

# Don't pull the predefined git repos
# pull_predefined = false

# Arguments to pass Git when pulling Repositories
# arguments = "--rebase --autostash"
