# https://k9scli.io/
# yaml-language-server: $schema=https://github.com/derailed/k9s/raw/refs/heads/master/internal/config/json/schemas/k9s.json
k9s:
  liveViewAutoRefresh: true
  refreshRate: 2
  apiServerTimeout: 15s
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: true
  portForwardAddress: localhost
  ui:
    enableMouse: false
    headless: true
    logoless: false
    crumbsless: false
    splashless: true
    reactive: true
    noIcons: false
    defaultsToFullScreen: true
    useFullGVRTitle: false
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    disableAutoscroll: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  defaultView: "pods all"
