# yamllint disable rule:document-start
# https://docs.github.com/actions

name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v5
      - run: ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
